import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/lib/redux/StoreProvider";
import { WalletProvider } from "@/components/providers/WalletProvider";
import { Toaster } from "@shelby-protocol/ui/components";
import { PostProvider } from "@/contexts/PostProvider";
import AuthProvider from "@/contexts/AuthProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <StoreProvider>
          <WalletProvider>
            <AuthProvider>
              <PostProvider>
                {children}
                <Toaster />
              </PostProvider>
            </AuthProvider>
          </WalletProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
